# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173-2R7QA8GTENs3qUBqBmrVjJsWZEw4r
"""

import os
import re
import sys
import json
import time
import subprocess
from collections import Counter

# ==========================================
# 1. 의존성 자가 검수 및 자동 설치 모듈
# ==========================================
def install_dependencies():
    required = {'pandas', 'openpyxl', 'requests'}
    try:
        import pandas
        import openpyxl
        import requests
    except ImportError:
        print("💡 [환경 진단] 필수 분석 패키지(pandas, openpyxl, requests)가 누락되었습니다.")
        print("💡 누락된 라이브러리 설치를 자동으로 개시합니다...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas", "openpyxl", "requests"])
            print("✅ [설치 완료] 모든 필수 분석 라이브러리가 성공적으로 구성되었습니다!\n")
        except Exception as e:
            print(f"❌ [에러] 패키지 자동 설치에 실패했습니다: {e}")
            print("수동으로 'pip install pandas openpyxl requests'를 실행해 주세요.")
            sys.exit(1)

# 자가 진단 실행
install_dependencies()

import pandas as pd
import requests

# ==========================================
# 2. 불용어(Stopwords) 사전 구축
# ==========================================
korean_stop_words = {
    '은', '는', '이', '가', '을', '를', '의', '에', '로', '으로', '에서', '에게', '한테', '과', '와',
    '도', '만', '고', '며', '이네', '이고', '이지만', '이며', '이다', '하고', '해서', '보다', '처럼', '조차', '마저',
    '요', '입니다', '합니다', '였다', '했다', '한다', '해', '한', '그', '이', '저', '것', '수', '등', '및', '즉',
    '또는', '더', '가장', '매우', '너무', '정말', '진짜', '완전', '아주', '조금', '약간', '많이', '드라마', '영화',
    '작품', '콘텐츠', '보고', '봤는데', '봤다', '시청', '봤어요', '때문에', '해서', '요즘', '다시', '하나', '역시',
    '대해', '대한', '통해', '위해', '정도', '때문', '경우', '사실', '모습', '생각', '사람', '우리', '그냥', '진짜'
}

english_stop_words = {
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself',
    'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself',
    'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that',
    'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
    'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because',
    'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into',
    'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out',
    'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where',
    'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no',
    'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just',
    'don', 'should', 'now', 'really', 'much', 'also', 'great', 'good', 'show', 'series', 'movie',
    'watch', 'watching', 'watched', 'think', 'thought', 'make', 'made', 'like', 'love', 'best', 'one', 'piece'
}

# 번역 결과 로컬 캐싱 파일
CACHE_FILE = "translation_cache.json"
translation_cache = {}

if os.path.exists(CACHE_FILE):
    try:
        with open(CACHE_FILE, 'r', encoding='utf-8') as f:
            translation_cache = json.load(f)
    except Exception:
        translation_cache = {}

def save_cache():
    try:
        with open(CACHE_FILE, 'w', encoding='utf-8') as f:
            json.dump(translation_cache, f, ensure_ascii=False, indent=4)
    except Exception as e:
        print(f"⚠️ [경고] 번역 캐시 파일 저장 실패: {e}")

# ==========================================
# 3. 텍스트 마이닝 헬퍼 함수
# ==========================================
def is_foreign_language(text):
    """리뷰 텍스트가 스페인어 등 비영어/비한국어인지 판별"""
    if not text or not isinstance(text, str) or text.strip() == "":
        return False
    # 한글이 포함되어 있는지 확인 -> 한국어 리뷰는 번역에서 제외
    has_korean = bool(re.search(r'[\uac00-\ud7a3]', text))
    if has_korean:
        return False

    # 특수 액센트 문자 확인 (스페인어, 프랑스어, 독일어 등)
    has_foreign_char = bool(re.search(r'[áéíóúñ¿¡çàèùâêîôûëïüöäßßæœÁÉÍÓÚÑÇÀÈÙÂÊÎÔÛËÏÜÖÄ]', text))
    if has_foreign_char:
        return True

    # 유럽계 다빈도 단어 확인 (스페인어, 프랑스어, 독일어 등)
    foreign_keywords = r'\b(el|la|los|las|de|en|que|y|un|una|es|muy|con|excelente|bueno|malo|pelicula|serie|le|les|des|du|et|une|est|pour|dans|avec|der|die|das|und|ist|in|mit|zu|von|se|non|si|un|una|pero)\b'
    if re.search(foreign_keywords, text, re.IGNORECASE):
        return True

    return False

def translate_to_english(text):
    """비한국어/비영어 텍스트를 실시간으로 영어로 번역 (Google Translate + MyMemory 이중화 및 캐싱)"""
    if not text or not isinstance(text, str) or text.strip() == "":
        return ""

    # 캐시 확인
    if text in translation_cache:
        return translation_cache[text]

    clean_text = text.replace('\n', ' ').replace('\r', ' ').strip()

    # 1단계: Google Translate gtx 무료 API 시도 (가장 빠르고 한도 제한 거의 없음)
    try:
        url = "https://translate.googleapis.com/translate_a/single"
        params = {
            "client": "gtx",
            "sl": "auto",
            "tl": "en",
            "dt": "t",
            "q": clean_text[:1000]
        }
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36"
        }
        response = requests.get(url, params=params, headers=headers, timeout=5)
        if response.status_code == 200:
            res_json = response.json()
            translated_sentences = []
            if res_json and len(res_json) > 0 and res_json[0]:
                for part in res_json[0]:
                    if part and len(part) > 0:
                        translated_sentences.append(part[0])
            if translated_sentences:
                translated = "".join(translated_sentences)
                translation_cache[text] = translated
                save_cache()
                return translated
    except Exception as e:
        # Google Translate 실패 시 MyMemory API로 자동 백업 이중화 우회
        pass

    # 2단계: MyMemory 번역 API 우회 시도
    try:
        url = f"https://api.mymemory.translated.net/get?q={requests.utils.quote(clean_text[:500])}&langpair=AUTO|en"
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            if 'responseData' in data and 'translatedText' in data['responseData']:
                translated = data['responseData']['translatedText']
                translation_cache[text] = translated
                save_cache()
                return translated
        elif response.status_code == 429:
            print(f"\n  ⚠️ [번역 트래픽 초과] MyMemory API 일일 한도가 초과되었습니다.")
    except Exception as e:
        print(f"\n  ⚠️ [번역 통신 에러] 번역 API 호출 중 예외 발생: {e}")
        print("  -> 인터넷 접속 상태 혹은 방화벽/샌드박스 네트워크 차단 설정을 점검해 주세요.")

    return text  # 모든 API 실패 시 원본 유지

def clean_korean_word(word):
    """한국어 조사 정밀 제거 필터"""
    if len(word) <= 1:
        return ""
    # 은/는/이/가/을/를/의/에/로/도 등 조사 제거 정규식
    word = re.sub(r'(은|는|이|가|을|를|의|에|로|으로|에서|에게|한테|과|와|도|만|고|며|이네|이고|이지만|이며|이다|하고|해서|보다|처럼|조차|마저|요|입니다|합니다|였다|했다|한다)$', '', word)
    if len(word) <= 1 or word in korean_stop_words:
        return ""
    return word

def clean_english_word(word):
    """영어 관사 및 불용어 제거 필터"""
    word = re.sub(r'[^a-z0-9]', '', word.lower())
    if len(word) <= 2 or word in english_stop_words:
        return ""
    return word

def extract_keywords(text):
    """텍스트에서 정제된 단어들을 주입하고 카운팅하는 형태소 분리기"""
    if not text or not isinstance(text, str):
        return []

    # 특수기호 거르고 띄어쓰기로 토큰 분리
    words = re.sub(r'[.,\/#!$%\^&\*;:{}=\-_`~()?]', '', text).split()
    cleaned_words = []

    for w in words:
        if len(w.strip()) <= 1:
            continue
        has_korean = bool(re.search(r'[\uac00-\ud7a3]', w))
        if has_korean:
            cleaned = clean_korean_word(w)
        else:
            cleaned = clean_english_word(w)

        if cleaned:
            cleaned_words.append(cleaned)

    return cleaned_words

# ==========================================
# 4. 파일 로더 및 헤더 지능 매핑 모듈
# ==========================================
def find_optimal_columns(df, filepath):
    """각 파일마다 제목, 평점, 리뷰내용에 부합하는 열 이름을 지능적으로 자동 탐색"""
    cols = df.columns.tolist()
    title_col, rating_col, review_col = None, None, None

    title_kws = ['제목', '작품', '프로그램', '콘텐츠', 'title', 'show', 'name', 'movie', 'series']
    rating_kws = ['별점', '평점', '점수', 'rating', 'score', 'star', '평가']
    review_kws = ['리뷰', '내용', '코멘트', '댓글', '텍스트', 'review', 'text', 'comment', 'content']

    # 1단계: 완전 매칭 또는 포함 매칭 탐색
    for col in cols:
        col_lower = str(col).lower()
        if any(kw in col_lower for kw in title_kws) and not title_col:
            title_col = col
        if any(kw in col_lower for kw in rating_kws) and not rating_col:
            rating_col = col
        if any(kw in col_lower for kw in review_kws) and not review_col:
            review_col = col

    # 2단계: 매핑 차선책 설정 (작품명이 없을 시 파일 이름을 작품명으로 스마트 승계)
    if not title_col:
        title_col = "auto_extracted_filename"
    if not rating_col:
        # 숫자 타입 데이터가 대다수 포함된 열로 강제 매핑 시도
        for col in cols:
            if df[col].dtype in ['int64', 'float64']:
                rating_col = col
                break
    if not review_col:
        # 가장 텍스트 길이가 긴 열로 강제 매핑 시도
        longest_avg = 0
        for col in cols:
            if df[col].dtype == 'object':
                avg_len = df[col].astype(str).str.len().mean()
                if avg_len > longest_avg:
                    longest_avg = avg_len
                    review_col = col

    return title_col, rating_col, review_col

# ==========================================
# 5. 핵심 구동 컨트롤러
# ==========================================
def main():
    print("=" * 60)
    print("🎬 스트리밍 18개 작품 리뷰 통합 텍스트 마이닝 시스템 🎬")
    print("=" * 60)

    target_dir = input("📁 분석할 엑셀 파일들이 위치한 폴더명을 입력해 주세요 (기본값: ./excel_reviews): ").strip()
    if not target_dir:
        target_dir = "./excel_reviews"

    if not os.path.exists(target_dir):
        print(f"❌ [에러] '{target_dir}' 폴더를 찾을 수 없습니다. 먼저 generate_sample_data.py를 실행하거나 올바른 경로를 기입해 주세요.")
        return

    # 폴더 내 파일 수집
    files = [f for f in os.listdir(target_dir) if f.endswith(('.xlsx', '.xls', '.csv'))]
    print(f"🔍 '{target_dir}' 폴더에서 총 {len(files)}개의 데이터 파일을 포착했습니다.")

    if len(files) == 0:
        print("❌ [에러] 폴더 내에 분석 가능한 엑셀(.xlsx) 또는 CSV(.csv) 파일이 존재하지 않습니다.")
        return

    all_records = []
    translated_count = 0

    # 10단계 평점 분류 통계 맵
    ratings_list = [5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5]
    rating_distribution = {r: 0 for r in ratings_list}
    keywords_by_rating = {r: {"words": Counter(), "reviews": []} for r in ratings_list}

    print("\n🚀 [1단계] 18개 작품 엑셀 파일 로드 및 통합 정제 시작...")

    for idx, filename in enumerate(files):
        filepath = os.path.join(target_dir, filename)
        file_base_name = os.path.splitext(filename)[0]

        # 파일 형식에 맞춰 유연한 판독
        try:
            if filename.endswith('.csv'):
                df = pd.read_csv(filepath)
            else:
                df = pd.read_excel(filepath)
        except Exception as e:
            print(f"  ❌ [{idx+1}/{len(files)}] 파일 읽기 실패 ({filename}): {e}")
            continue

        if df.empty:
            print(f"  ⚠️ [{idx+1}/{len(files)}] 데이터가 없어 제외됨 ({filename})")
            continue

        # 지능형 열 이름 검색
        t_col, r_col, rev_col = find_optimal_columns(df, filepath)

        # 실제 데이터 파싱
        rows_processed = 0
        for _, row in df.iterrows():
            # 작품명
            if t_col == "auto_extracted_filename":
                show_title = re.sub(r'^\d+_', '', file_base_name).replace('_reviews', '').replace('_', ' ').title()
            else:
                show_title = str(row.get(t_col, "미확인 작품"))

            # 리뷰 텍스트
            original_review = str(row.get(rev_col, ""))
            if not original_review or original_review.strip() == "nan":
                continue

            # 평점 10단계 매핑 및 스케일링
            try:
                rating_val = float(row.get(r_col, 0.0))
            except ValueError:
                rating_val = 0.0

            # 스케일 변환 (10점이나 100점 만점을 5점 만점 단위로 조율)
            if rating_val > 5 and rating_val <= 10:
                normalized_rating = rating_val / 2
            elif rating_val > 10 and rating_val <= 100:
                normalized_rating = rating_val / 20
            else:
                normalized_rating = rating_val

            # 0.5점 단위로 10개 바스켓 바인딩
            bucket = round(normalized_rating * 2) / 2
            if bucket > 5.0: bucket = 5.0
            if bucket < 0.5: bucket = 0.5

            # 다국어 실시간 영어 번역
            is_trans = False
            mining_text = original_review
            if is_foreign_language(original_review):
                translated_text = translate_to_english(original_review)
                if translated_text != original_review:
                    is_trans = True
                    mining_text = translated_text
                    translated_count += 1

            # 형태소 필터 단어 마이닝
            keywords = extract_keywords(mining_text)

            # 레코드 정보 통합 구성
            record = {
                "title": show_title,
                "original_review": original_review,
                "mining_text": mining_text,
                "rating": rating_val,
                "normalized_rating": normalized_rating,
                "bucket": bucket,
                "is_translated": is_trans,
                "keywords": keywords
            }

            all_records.append(record)
            rating_distribution[bucket] += 1
            keywords_by_rating[bucket]["words"].update(keywords)
            keywords_by_rating[bucket]["reviews"].append(record)
            rows_processed += 1

        print(f"  ✅ [{idx+1}/{len(files)}] 로드 성공: '{show_title}' ({rows_processed}건의 리뷰 통합 완료)")

    total_reviews = len(all_records)
    if total_reviews == 0:
        print("❌ [실패] 통합된 데이터가 없어 텍스트 마이닝을 진행할 수 없습니다.")
        return

    print(f"\n📊 [통합 결과] 총 {len(files)}개 파일 병합 | 총 리뷰 {total_reviews}건 | 번역 적용 {translated_count}건")

    # ==========================================
    # 6. 정량 텍스트 마이닝 결과 연산 및 기획 전략 도출
    # ==========================================
    print("\n⚡ [2단계] 별점 등급별 다빈도 키워드 연산 및 기획 인사이트 추출 중...")

    # 긍정(4.0~5.0) 및 부정(0.5~2.5) 전체 키워드 종합
    overall_pos_words = Counter()
    overall_neg_words = Counter()

    for r in ratings_list:
        if r >= 4.0:
            overall_pos_words.update(keywords_by_rating[r]["words"])
        elif r <= 2.5:
            overall_neg_words.update(keywords_by_rating[r]["words"])

    # 1위 ~ 10위 빈도 키워드 추출
    top_pos_keywords = overall_pos_words.most_common(12)
    top_neg_keywords = overall_neg_words.most_common(12)

    # 콘텐츠 추천 장르 규칙 적용 기획서 제안
    recommended_genre = "밀도 높은 사건 추리 및 미스터리 스릴러극"
    genre_rules = [
        "빠른 템포 중심의 서사 구조 기획",
        "불필요한 빌드업을 지우고 곧바로 갈등이 치솟는 씬 배치"
    ]

    pos_keys = [w[0] for w in top_pos_keywords]
    neg_keys = [w[0] for w in top_neg_keywords]

    has_cgi = any(w in pos_keys for w in ['cg', 'cgi', '비주얼', '영상미', 'effects', 'visuals'])
    has_action = any(w in pos_keys for w in ['액션', 'action', '격투', '전투'])
    has_romance = any(w in pos_keys for w in ['로맨스', 'romance', '러브', '감정선', 'love'])

    if has_cgi and has_action:
        recommended_genre = "VFX 기술을 접목한 고품격 크리처물 및 SF 액션 블록버스터"
        genre_rules = [
            "압도적 몰입감을 위한 풍성한 스펙터클 시각 특수효과 연출",
            "글로벌 타겟팅에 유리한 빠른 속도감 중심의 비주얼 갈등 라인 설계"
        ]
    elif has_romance:
        recommended_genre = "감정선의 밀도가 높은 휴먼 정서형 멜로/일상 오피스 드라마"
        genre_rules = [
            "억지 신파나 작위적 눈물을 배제하고, 섬세한 주연진 연기력 중심 배치",
            "매력적인 서브 캐릭터 간 케미스트리를 극대화하여 과도한 답답함 분산"
        ]
    elif '스릴러' in pos_keys or '반전' in pos_keys or 'suspense' in pos_keys:
        recommended_genre = "숨 가쁜 몰입감을 선사하는 독창적인 반전 스릴러극"
        genre_rules = [
            "초반부터 명확한 Hook을 던져 시청자 이탈 최소화",
            "매화 결말부에 강력한 클리프행어(다음 화 유도 장치) 배치"
        ]

    # ==========================================
    # 7. 기획 보고서 엑셀 파일 저장 (openpyxl 스타일)
    # ==========================================
    report_xlsx = "streaming_review_analysis_report.xlsx"
    print(f"\n📥 [3단계] 상세 분석 엑셀 보고서 빌드 중... ({report_xlsx})")

    with pd.ExcelWriter(report_xlsx, engine='openpyxl') as writer:
        # 시트 1: 개요 요약
        summary_rows = [
            ["분석 일자", time.strftime("%Y-%m-%d %H:%M:%S")],
            ["총 수집/통합 리뷰 수", total_reviews],
            ["분석 완료된 개별 작품 수", len(files)],
            ["평균 별점 (5점 만점 변환 기준)", round(sum(d["normalized_rating"] for d in all_records)/total_reviews, 3)],
            ["다국어 실시간 영어 번역 처리 수", translated_count]
        ]
        pd.DataFrame(summary_rows, columns=["핵심 성과지표(KPI)", "통계 수치"]).to_excel(writer, sheet_name="분석 요약", index=False)

        # 시트 2: 10단계 리뷰 분류 데이터
        classified_rows = []
        for d in all_records:
            classified_rows.append({
                "작품명": d["title"],
                "입력 원본별점": d["rating"],
                "5점 척도 스케일링": round(d["normalized_rating"], 2),
                "10단계 바스켓": d["bucket"],
                "실시간 번역 적용 여부": "Y" if d["is_translated"] else "N",
                "리뷰 원문": d["original_review"],
                "텍스트 마이닝 대상문 (번역/정제)": d["mining_text"]
            })
        pd.DataFrame(classified_rows).to_excel(writer, sheet_name="10단계 리뷰 세부 매핑", index=False)

        # 시트 3: 등급별 다빈도 키워드 통계표
        freq_rows = []
        for r in ratings_list:
            words = keywords_by_rating[r]["words"]
            for word, count in words.most_common(15):
                freq_rows.append({
                    "별점 바스켓": f"{r:.1f}점",
                    "단어": word,
                    "출현 빈도수": count
                })
        pd.DataFrame(freq_rows).to_excel(writer, sheet_name="평점 구간별 다빈도 단어", index=False)

        # 시트 4: 콘텐츠 기획 전략 가이드라인
        strategy_rows = [
            ["권장 기획 장르", recommended_genre],
            ["핵심 연출 규칙 1", genre_rules[0]],
            ["핵심 연출 규칙 2", genre_rules[1]],
            ["시청자 열광 포인트 (흥미 요인 탑 3)", ", ".join([w[0] for w in top_pos_keywords[:5]])],
            ["시청자 피로 포인트 (개선해야 할 요인 탑 3)", ", ".join([w[0] for w in top_neg_keywords[:5]])]
        ]
        pd.DataFrame(strategy_rows, columns=["기획 영역", "전략 가이드라인"]).to_excel(writer, sheet_name="신작 기획 전략서", index=False)

    print(f"  🎉 엑셀 분석 보고서 컴파일 완료! -> {report_xlsx}")

    # ==========================================
    # 8. 인터랙티브 대화형 HTML 대시보드 빌드
    # ==========================================
    report_html = "dashboard_report.html"
    print(f"📥 [4단계] 대화형 HTML 대시보드 빌드 중... ({report_html})")

    # 10단계 탭용 데이터 구조화
    tab_data_js = {}
    for r in ratings_list:
        words = keywords_by_rating[r]["words"]
        reviews = keywords_by_rating[r]["reviews"]

        tab_data_js[str(r)] = {
            "top_words": [[word, count] for word, count in words.most_common(12)],
            "reviews": [{
                "title": r_item["title"],
                "original": r_item["original_review"],
                "rating": float(r_item["rating"]),
                "is_trans": r_item["is_translated"]
            } for r_item in reviews[:5]]  # 각 탭당 대표 리뷰 5건
        }

    # 전체 흥미/아쉬움 요인 매칭 슬라이더용 데이터
    interest_words_js = [[word, count] for word, count in top_pos_keywords]
    disappointment_words_js = [[word, count] for word, count in top_neg_keywords]

    # 매칭 문장 (Context Explorer 용 데이터 탑재)
    context_data_js = []
    for d in all_records:
        context_data_js.append({
            "title": d["title"],
            "original": d["original_review"],
            "cleaned": d["mining_text"],
            "rating": float(d["rating"]),
            "bucket": float(d["bucket"]),
            "is_trans": d["is_translated"]
        })

    # Jinja2 템플릿 대체용 인라인 HTML 문자열 조립
    html_content = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>스트리밍 콘텐츠 리뷰 텍스트 마이닝 대시보드</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;600;700;800&family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root {{
            --bg-color: #0b0f19;
            --card-bg: rgba(17, 24, 39, 0.7);
            --card-border: rgba(255, 255, 255, 0.08);
            --text-primary: #f3f4f6;
            --text-secondary: #9ca3af;
            --primary: #8b5cf6;
            --primary-glow: rgba(139, 92, 246, 0.4);
            --secondary: #3b82f6;
            --accent: #ec4899;
            --success: #10b981;
            --warning: #f59e0b;
            --danger: #ef4444;
            --glass-blur: blur(16px);
            --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: 'Noto Sans KR', 'Inter', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
            background-image:
                radial-gradient(circle at 10% 20%, rgba(139, 92, 246, 0.15) 0%, transparent 40%),
                radial-gradient(circle at 90% 80%, rgba(59, 130, 246, 0.15) 0%, transparent 40%);
            background-attachment: fixed;
            padding-bottom: 60px;
        }}
        .container {{ max-width: 1400px; margin: 0 auto; padding: 40px 20px; }}
        header {{ text-align: center; margin-bottom: 40px; }}
        .badge {{
            display: inline-block; padding: 6px 14px;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            border-radius: 20px; font-size: 0.85rem; font-weight: 600;
            letter-spacing: 1px; margin-bottom: 16px;
            box-shadow: 0 4px 15px var(--primary-glow);
            font-family: 'Outfit', sans-serif;
        }}
        h1 {{
            font-family: 'Outfit', 'Noto Sans KR', sans-serif;
            font-size: 2.8rem; font-weight: 800;
            background: linear-gradient(to right, #ffffff, #c084fc, #6366f1);
            -webkit-background-clip: text; -webkit-text-fill-color: transparent;
            margin-bottom: 12px; letter-spacing: -0.5px;
        }}
        header p {{ color: var(--text-secondary); font-size: 1.1rem; max-width: 600px; margin: 0 auto; }}
        .panel {{
            background: var(--card-bg); border: 1px solid var(--card-border);
            border-radius: 24px; backdrop-filter: var(--glass-blur);
            -webkit-backdrop-filter: var(--glass-blur); padding: 30px;
            margin-bottom: 30px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
            transition: var(--transition);
        }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; margin-bottom: 30px; }}
        .stat-card {{
            background: var(--card-bg); border: 1px solid var(--card-border);
            border-radius: 20px; padding: 24px; display: flex; align-items: center; gap: 20px;
        }}
        .stat-icon {{
            width: 54px; height: 54px; border-radius: 14px;
            display: flex; align-items: center; justify-content: center; font-size: 1.5rem;
        }}
        .stat-icon.blue {{ background: rgba(59, 130, 246, 0.15); color: #3b82f6; }}
        .stat-icon.purple {{ background: rgba(139, 92, 246, 0.15); color: #8b5cf6; }}
        .stat-icon.emerald {{ background: rgba(16, 185, 129, 0.15); color: #10b981; }}
        .stat-icon.rose {{ background: rgba(244, 63, 94, 0.15); color: #f43f5e; }}
        .stat-info h4 {{ font-size: 0.9rem; color: var(--text-secondary); font-weight: 500; }}
        .stat-info p {{ font-size: 1.8rem; font-weight: 700; font-family: 'Outfit', sans-serif; color: var(--text-primary); margin-top: 4px; }}

        .chart-section {{ display: grid; grid-template-columns: 3fr 2fr; gap: 30px; margin-bottom: 30px; }}
        @media (max-width: 1024px) {{ .chart-section {{ grid-template-columns: 1fr; }} }}
        .chart-box {{ min-height: 350px; display: flex; align-items: center; justify-content: center; width: 100%; }}

        .sentiment-split {{ display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 30px; }}
        @media (max-width: 768px) {{ .sentiment-split {{ grid-template-columns: 1fr; }} }}
        .split-column {{ display: flex; flex-direction: column; gap: 20px; }}
        .split-header {{ display: flex; align-items: center; gap: 12px; font-size: 1.3rem; font-weight: 700; border-bottom: 2px solid; padding-bottom: 12px; }}
        .split-header.interest {{ color: var(--success); border-color: rgba(16, 185, 129, 0.2); }}
        .split-header.disappointment {{ color: var(--danger); border-color: rgba(239, 68, 68, 0.2); }}

        .sentiment-word-grid {{ display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 15px; }}
        .sentiment-word {{
            padding: 8px 16px; border-radius: 12px; font-size: 0.95rem; font-weight: 600;
            display: flex; align-items: center; gap: 8px; cursor: pointer; transition: var(--transition);
        }}
        .interest .sentiment-word {{ background: rgba(16, 185, 129, 0.08); border: 1px solid rgba(16, 185, 129, 0.15); color: #a7f3d0; }}
        .interest .sentiment-word:hover, .interest .sentiment-word.active {{ background: var(--success); color: #064e3b; box-shadow: 0 0 15px rgba(16, 185, 129, 0.3); }}
        .disappointment .sentiment-word {{ background: rgba(239, 68, 68, 0.08); border: 1px solid rgba(239, 68, 68, 0.15); color: #fecaca; }}
        .disappointment .sentiment-word:hover, .disappointment .sentiment-word.active {{ background: var(--danger); color: #7f1d1d; box-shadow: 0 0 15px rgba(239, 68, 68, 0.3); }}
        .sentiment-word span {{ background: rgba(0, 0, 0, 0.2); padding: 2px 6px; border-radius: 6px; font-size: 0.8rem; font-weight: 500; }}

        .context-explorer {{ background: rgba(0, 0, 0, 0.2); border-radius: 16px; padding: 20px; border: 1px solid var(--card-border); margin-top: 15px; }}
        .context-title {{ font-size: 0.95rem; color: var(--text-secondary); margin-bottom: 12px; }}
        .snippet-card {{ background: rgba(255, 255, 255, 0.02); border-left: 4px solid var(--primary); padding: 14px 18px; border-radius: 0 12px 12px 0; margin-bottom: 12px; font-size: 0.95rem; }}
        .snippet-meta {{ display: flex; justify-content: space-between; font-size: 0.8rem; color: var(--text-secondary); margin-top: 8px; }}
        .snippet-meta .rating-tag {{ background: var(--primary-glow); color: #d8b4fe; padding: 2px 6px; border-radius: 4px; }}
        .highlight {{ background: rgba(245, 158, 11, 0.25); border-bottom: 2px solid var(--warning); padding: 0 2px; color: #fbbf24; font-weight: 500; }}

        .tabs-header {{ display: flex; overflow-x: auto; gap: 10px; padding-bottom: 12px; margin-bottom: 24px; border-bottom: 1px solid var(--card-border); }}
        .tab-btn {{ padding: 10px 18px; background: rgba(255, 255, 255, 0.04); border: 1px solid var(--card-border); border-radius: 12px; color: var(--text-secondary); font-weight: 500; cursor: pointer; white-space: nowrap; transition: var(--transition); }}
        .tab-btn.active {{ background: linear-gradient(135deg, var(--primary), var(--secondary)); color: white; border-color: transparent; box-shadow: 0 4px 12px var(--primary-glow); }}
        .tab-content {{ display: none; }}
        .tab-content.active {{ display: block; }}

        .strategy-container {{ display: grid; grid-template-columns: 1fr 1fr; gap: 30px; }}
        @media (max-width: 768px) {{ .strategy-container {{ grid-template-columns: 1fr; }} }}
        .strategy-box {{ background: rgba(255, 255, 255, 0.02); border: 1px solid var(--card-border); border-radius: 16px; padding: 24px; position: relative; overflow: hidden; }}
        .strategy-box::before {{ content: ""; position: absolute; top: 0; left: 0; width: 4px; height: 100%; }}
        .strategy-box.success::before {{ background: var(--success); }}
        .strategy-box.danger::before {{ background: var(--danger); }}
        .strategy-box.primary::before {{ background: var(--primary); }}
        .strategy-box h4 {{ font-size: 1.15rem; font-weight: 700; margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }}
        .strategy-box.success h4 {{ color: #6ee7b7; }}
        .strategy-box.danger h4 {{ color: #fca5a5; }}
        .strategy-box.primary h4 {{ color: #d8b4fe; }}
        .strategy-list {{ list-style: none; }}
        .strategy-list li {{ margin-bottom: 12px; padding-left: 20px; position: relative; font-size: 0.95rem; }}
        .strategy-list li::before {{ content: "•"; position: absolute; left: 0; font-size: 1.2rem; line-height: 1; }}
        .strategy-box.success .strategy-list li::before {{ color: var(--success); }}
        .strategy-box.danger .strategy-list li::before {{ color: var(--danger); }}
        .strategy-box.primary .strategy-list li::before {{ color: var(--primary); }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <span class="badge">Streaming Review Python Analyzer</span>
            <h1>스트리밍 작품 리뷰 종합 마이닝 대시보드</h1>
            <p>18개 작품 데이터 파일 자동 로드, 스페인어 실시간 번역, 10단계 분류 및 기획 가이드 리포트</p>
        </header>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon blue">🎬</div>
                <div class="stat-info">
                    <h4>총 통합 분석 작품</h4>
                    <p>{len(files)}개</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon purple">📝</div>
                <div class="stat-info">
                    <h4>총 취합 리뷰수</h4>
                    <p>{total_reviews}건</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon emerald">⭐</div>
                <div class="stat-info">
                    <h4>종합 평균 별점</h4>
                    <p>{sum(d["normalized_rating"] for d in all_records)/total_reviews:.2f} / 5.0</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon rose">🌐</div>
                <div class="stat-info">
                    <h4>실시간 자동 번역</h4>
                    <p>{translated_count}건</p>
                </div>
            </div>
        </div>

        <div class="chart-section">
            <div class="panel">
                <h3 style="margin-bottom: 20px; font-weight: 700;">별점 10단계 구간별 분포도</h3>
                <div class="chart-box">
                    <canvas id="ratingChart"></canvas>
                </div>
            </div>
            <div class="panel" style="display: flex; flex-direction: column; justify-content: center;">
                <h3 style="margin-bottom: 16px; font-weight: 700; color: #a78bfa;">📊 평점 10개 구간 분포 요약</h3>
                <p style="color: var(--text-secondary); margin-bottom: 20px; font-size: 0.95rem;">각 엑셀 데이터의 평점(별점)을 0.5점 단위의 10개 카테고리로 통일화하여 축적한 비중 표입니다.</p>
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                    {"".join([f'<div style="padding: 8px 12px; background: rgba(255,255,255,0.02); border: 1px solid var(--card-border); border-radius: 8px; display: flex; justify-content: space-between; font-size: 0.9rem;"><span style="font-weight:600; color:#d8b4fe;">★ {r:.1f}점</span><span>{rating_distribution[r]}건 ({rating_distribution[r]/total_reviews*100:.1f}%)</span></div>' for r in ratings_list])}
                </div>
            </div>
        </div>

        <div class="sentiment-split">
            <div class="panel split-column">
                <div class="split-header interest"><span>🔥</span> 흥미/매력 요인 (고평가 키워드)</div>
                <p style="color: var(--text-secondary); font-size: 0.9rem;">평점 4.0 ~ 5.0점의 고평가 리뷰에서 두드러지게 언급된 시청 포인트입니다.</p>
                <div class="sentiment-word-grid" id="interest-words"></div>
                <div class="context-explorer">
                    <div class="context-title">💬 흥미 유발 코멘트 Context Explorer</div>
                    <div id="interest-snippets"><p style="color: var(--text-secondary); font-size: 0.9rem;">키워드를 클릭하여 원본 피드백의 문맥을 탐색해 보세요.</p></div>
                </div>
            </div>
            <div class="panel split-column">
                <div class="split-header disappointment"><span>⚠️</span> 아쉬움/피로 요인 (저평가 키워드)</div>
                <p style="color: var(--text-secondary); font-size: 0.9rem;">평점 0.5 ~ 2.5점의 저평가 리뷰에서 드러난 주요 단점 및 스트레스 원인입니다.</p>
                <div class="sentiment-word-grid" id="disappointment-words"></div>
                <div class="context-explorer">
                    <div class="context-title">💬 아쉬움 토로 코멘트 Context Explorer</div>
                    <div id="disappointment-snippets"><p style="color: var(--text-secondary); font-size: 0.9rem;">키워드를 클릭하여 원본 피드백의 문맥을 탐색해 보세요.</p></div>
                </div>
            </div>
        </div>

        <div class="panel">
            <h3 style="margin-bottom: 12px; font-weight: 700;">10개 별점 구간별 개별 키워드 정밀 마이닝</h3>
            <p style="color: var(--text-secondary); margin-bottom: 24px; font-size: 0.95rem;">별점 탭을 눌러 해당 점수를 부여한 시청층의 Top 10 다빈도 어휘 및 코멘트를 모니터링합니다.</p>
            <div class="tabs-header" id="tabs-header"></div>
            <div id="tabs-contents"></div>
        </div>

        <div class="panel">
            <h3 style="margin-bottom: 16px; font-weight: 700; background: linear-gradient(to right, #ffffff, #a78bfa); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">💡 데이터 마이닝 기반 콘텐츠 기획 전략 제안</h3>
            <p style="color: var(--text-secondary); margin-bottom: 24px; font-size: 0.95rem;">18개 콘텐츠 분석 데이터의 통합 마이닝 결과지를 근거로 산출한 콘텐츠 흥행 공식 가이드라인입니다.</p>
            <div class="strategy-container">
                <div class="strategy-box primary">
                    <h4>🎬 추천 제작 장르</h4>
                    <ul class="strategy-list">
                        <li><strong>추천 장르:</strong> {recommended_genre}</li>
                        <li>{genre_rules[0]}</li>
                        <li>{genre_rules[1]}</li>
                    </ul>
                </div>
                <div class="strategy-box success">
                    <h4>✅ 탑재 필수 요소 (흥미 자극제)</h4>
                    <ul class="strategy-list">
                        {"".join([f"<li><strong>{w[0]}:</strong> 고평가 피드백 내 핵심 언급 ({w[1]}회 출현)</li>" for w in top_pos_keywords[:4]])}
                    </ul>
                </div>
                <div class="strategy-box danger">
                    <h4>❌ 완화/지양 요소 (위험 차단제)</h4>
                    <ul class="strategy-list">
                        {"".join([f"<li><strong>{w[0]}:</strong> 저평가 및 불만 요소 내 핵심 언급 ({w[1]}회 출현)</li>" for w in top_neg_keywords[:4]])}
                    </ul>
                </div>
                <div class="strategy-box primary">
                    <h4>🎯 흥행 연출 안전 공식</h4>
                    <ul class="strategy-list">
                        <li>고점 단어 [ {top_pos_keywords[0][0] if len(top_pos_keywords)>0 else "스토리"} ]와 [ {top_pos_keywords[1][0] if len(top_pos_keywords)>1 else "몰입감"} ]를 활용한 핵심 메인 플롯 설계.</li>
                        <li>저점 단어 [ {top_neg_keywords[0][0] if len(top_neg_keywords)>0 else "지루함"} ] 요소를 사전 모니터링 단계에서 극력 방지 및 시나리오 롤백 실행.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        const tabData = {json.dumps(tab_data_js, ensure_ascii=False)};
        const interestWords = {json.dumps(interest_words_js, ensure_ascii=False)};
        const disappointmentWords = {json.dumps(disappointment_words_js, ensure_ascii=False)};
        const contextData = {json.dumps(context_data_js, ensure_ascii=False)};
        const ratingsList = {json.dumps(ratings_list)};

        window.onload = function() {{
            drawRatingChart();
            renderKeywordsList('interest-words', interestWords, true);
            renderKeywordsList('disappointment-words', disappointmentWords, false);
            renderRatingTabs();
        }};

        function drawRatingChart() {{
            const ctx = document.getElementById('ratingChart').getContext('2d');
            const counts = ratingsList.map(r => {json.dumps(rating_distribution)}[r] || 0);

            new Chart(ctx, {{
                type: 'bar',
                data: {{
                    labels: ratingsList.map(r => r.toFixed(1) + "점"),
                    datasets: [{{
                        label: '리뷰 수(건)',
                        data: counts,
                        backgroundColor: [
                            'rgba(139, 92, 246, 0.75)', 'rgba(139, 92, 246, 0.65)',
                            'rgba(99, 102, 241, 0.75)', 'rgba(99, 102, 241, 0.65)',
                            'rgba(59, 130, 246, 0.75)', 'rgba(59, 130, 246, 0.65)',
                            'rgba(245, 158, 11, 0.75)', 'rgba(245, 158, 11, 0.65)',
                            'rgba(239, 68, 68, 0.75)', 'rgba(239, 68, 68, 0.65)'
                        ],
                        borderRadius: 8
                    }}]
                }},
                options: {{
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {{ legend: {{ display: false }} }},
                    scales: {{
                        y: {{ beginAtZero: true, grid: {{ color: 'rgba(255, 255, 255, 0.05)' }}, ticks: {{ color: '#9ca3af' }} }},
                        x: {{ grid: {{ display: false }}, ticks: {{ color: '#9ca3af' }} }}
                    }}
                }}
            }});
        }}

        function renderKeywordsList(containerId, wordsList, isPositive) {{
            const container = document.getElementById(containerId);
            container.innerHTML = '';
            wordsList.forEach(([word, count]) => {{
                const el = document.createElement('div');
                el.className = 'sentiment-word';
                el.innerHTML = word + " <span>" + count + "</span>";
                el.addEventListener('click', () => {{
                    const selector = isPositive ? '#interest-words .sentiment-word' : '#disappointment-words .sentiment-word';
                    document.querySelectorAll(selector).forEach(c => c.classList.remove('active'));
                    el.classList.add('active');
                    showWordContext(word, isPositive);
                }});
                container.appendChild(el);
            }});
        }}

        function showWordContext(word, isPositive) {{
            const containerId = isPositive ? 'interest-snippets' : 'disappointment-snippets';
            const container = document.getElementById(containerId);
            container.innerHTML = '';

            const matches = contextData.filter(d => {{
                const isPosMatch = isPositive ? d.bucket >= 4.0 : d.bucket <= 2.5;
                const hasWord = d.cleaned.toLowerCase().includes(word.toLowerCase()) || d.original.includes(word);
                return isPosMatch && hasWord;
            }}).slice(0, 4);

            if (matches.length === 0) {{
                container.innerHTML = "<p style='color:var(--text-secondary); font-size:0.9rem;'>매칭되는 실질 피드백 문맥이 발견되지 않았습니다.</p>";
                return;
            }}

            matches.forEach(m => {{
                const snippet = document.createElement('div');
                snippet.className = 'snippet-card';
                const regex = new RegExp("(" + word + ")", 'gi');
                const highlightedText = m.original.replace(regex, '<span class="highlight">$1</span>');
                let metaTrans = m.is_trans ? "<br><small style='color:var(--primary); font-size:0.8rem;'>🔄 번역 원문: " + m.cleaned.replace(regex, '<span class="highlight">$1</span>') + "</small>" : "";

                snippet.innerHTML = "<div>\\"" + highlightedText + "\\"</div>" + metaTrans + "<div class='snippet-meta'><span>🎬 " + m.title + "</span><span class='rating-tag'>★ " + m.rating.toFixed(1) + "점</span></div>";
                container.appendChild(snippet);
            }});
        }}

        function renderRatingTabs() {{
            const tabsHeader = document.getElementById('tabs-header');
            const tabsContents = document.getElementById('tabs-contents');

            ratingsList.forEach((r, idx) => {{
                const rStr = r.toString().replace('.', '_');

                const btn = document.createElement('button');
                btn.className = "tab-btn " + (idx === 0 ? 'active' : '');
                btn.innerText = "★ " + r.toFixed(1) + "점";
                btn.addEventListener('click', () => {{
                    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
                    btn.classList.add('active');
                    document.getElementById('tab-' + rStr).classList.add('active');
                }});
                tabsHeader.appendChild(btn);

                const contentBox = document.createElement('div');
                contentBox.className = "tab-content " + (idx === 0 ? 'active' : '');
                contentBox.id = 'tab-' + rStr;

                const data = tabData[r.toString()];
                let wordsHtml = '<div style="display:flex; flex-wrap:wrap; gap:8px; margin-bottom:20px;">';
                if (data.top_words.length === 0) {{
                    wordsHtml = '<p style="color:var(--text-secondary);">추출된 다빈도 어휘가 존재하지 않습니다.</p>';
                }} else {{
                    data.top_words.forEach(([w, count]) => {{
                        wordsHtml += "<span style='background:rgba(255,255,255,0.05); padding:6px 12px; border-radius:8px; font-size:0.9rem; border:1px solid rgba(255,255,255,0.05);'>" + w + " (" + count + "회)</span>";
                    }});
                    wordsHtml += '</div>';
                }}

                let reviewsHtml = '';
                if (data.reviews.length === 0) {{
                    reviewsHtml = '<p style="color:var(--text-secondary);">수집된 리뷰가 존재하지 않습니다.</p>';
                }} else {{
                    reviewsHtml = '<h4 style="font-size:0.95rem; color:#c084fc; margin-bottom:10px;">💬 대표 리뷰 피드백 목록</h4>';
                    data.reviews.forEach(sr => {{
                        let labelTrans = sr.is_trans ? "<span style='color:var(--secondary); font-size:0.75rem; border:1px solid; border-radius:3px; padding:1px 3px; margin-left:8px;'>번역됨</span>" : "";
                        reviewsHtml += "<div style='background:rgba(255,255,255,0.01); border-left:3px solid var(--primary); padding:10px 14px; border-radius:0 8px 8px 0; margin-bottom:10px; font-size:0.9rem;'><div>\\"" + sr.original + "\\" " + labelTrans + "</div><div style='display:flex; justify-content:space-between; font-size:0.8rem; color:var(--text-secondary); margin-top:6px;'><span>🎥 " + sr.title + "</span><span>★ " + sr.rating + "점</span></div></div>";
                    }});
                }}

                contentBox.innerHTML = "<h3 style='font-size:1.15rem; margin-bottom:12px; font-weight:600; color:#d8b4fe;'>★ " + r.toFixed(1) + "점 상세 마이닝 분석</h3><h4 style='font-size:0.95rem; color:var(--text-secondary); margin-bottom:10px;'>🏷️ 대표 다빈도 키워드</h4>" + wordsHtml + reviewsHtml;
                tabsContents.appendChild(contentBox);
            }});
        }}
    </script>
</body>
</html>
"""

    with open(report_html, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"  🎉 대화형 HTML 대시보드 컴파일 완료! -> {report_html}")

    print("\n" + "=" * 60)
    print("✅ [분석 종료] 18개 작품 텍스트 마이닝 작업이 완전히 종료되었습니다!")
    print(f"  - 상세 엑셀 분석 보고서 : {os.path.abspath(report_xlsx)}")
    print(f"  - 대화형 HTML 대시보드   : {os.path.abspath(report_html)}")
    print("=" * 60)

if __name__ == "__main__":
    main()

