# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFQniQdmCzXt0_3heHXcL86gf1tkAa6X
"""

import requests
import pandas as pd
import re
import time
from urllib.parse import urlparse, parse_qs
from getpass import getpass
from google.colab import files
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

print("셀 1 완료: 필요한 도구를 불러왔습니다.")

API_KEY = getpass("AIzaSyDIst91gjc_3l83YZfMo3UW1pVDChZdJ_I")

print("셀 2 완료: API 키가 입력되었습니다.")

COMMENTS_PER_VIDEO = 100

works = [
    {
        "title": "The Lincoln Lawyer",
        "urls": [
            "https://www.youtube.com/watch?v=pVvVNbLf7Ig",
            "https://www.youtube.com/watch?v=8Q3jJA60jWo"
        ]
    },
    {
        "title": "The Night Agent",
        "urls": [
            "https://www.youtube.com/watch?v=YDbnY9Obsfs",
            "https://www.youtube.com/watch?v=rgULl9Qi2WM"
        ]
    },
    {
        "title": "Unfamiliar",
        "urls": [
            "https://www.youtube.com/watch?v=RY-FSHJ7fKA"
        ]
    },
    {
        "title": "Virgin River",
        "urls": [
            "https://www.youtube.com/watch?v=DMNjH5MlQXc",
            "https://www.youtube.com/watch?v=7tAQ4CPNvY4"
        ]
    },
     {
        "title": "Alpha Males",
        "urls": [
            "https://www.youtube.com/watch?v=NpimczviUHA",
            "https://www.youtube.com/watch?v=HtPxmKxGSOI"
        ]
    },
     {
        "title": "Bloodhounds",
        "urls": [
            "https://www.youtube.com/watch?v=eyiR8pO50JE",
            "https://www.youtube.com/watch?v=g4WrSJZD10M"
        ]
    },
     {
        "title": "Boyfriend on Demand",
        "urls": [
            "https://www.youtube.com/watch?v=A0GqKTgSpuE",
            "https://www.youtube.com/watch?v=Z-ZcZC4RiQM"
        ]
    },
     {
        "title": "Bridgerton",
        "urls": [
            "https://www.youtube.com/watch?v=gpv7ayf_tyE",
            "https://www.youtube.com/watch?v=Bs9r1UbmFAI"
        ]
    },
     {
        "title": "Detective Hole",
        "urls": [
            "https://www.youtube.com/watch?v=QozBsgrEjnE",
            "https://www.youtube.com/watch?v=BRt7ojFIwzs"
        ]
    },
     {
        "title": "His&Hers",
        "urls": [
            "https://www.youtube.com/watch?v=8_szlvBLll0",
            "https://www.youtube.com/watch?v=fczHduoIN-U"
        ]
    },
     {
        "title": "Love is Blind",
        "urls": [
            "https://www.youtube.com/watch?v=s2eBAFt3L_0",
            "https://www.youtube.com/watch?v=yFVKSx50PBY"
        ]
    },
     {
        "title": "One Piece",
        "urls": [
            "https://www.youtube.com/watch?v=Ades3pQbeh8",
            "https://www.youtube.com/watch?v=S-XxKVxZ2fU"
        ]
    },
     {
        "title": "Radioactive Emergency",
        "urls": [
            "https://www.youtube.com/watch?v=Dsq4d6repjg"
        ]
    },
     {
        "title": "Salish Jorand Matter",
        "urls": [
            "https://www.youtube.com/watch?v=ypPWAObvh1k",
            "https://www.youtube.com/watch?v=1FPJxGYElBo"
        ]
    },
     {
        "title": "Salvador",
        "urls": [
            "https://www.youtube.com/watch?v=L_xcb8YRUe0",
            "https://www.youtube.com/watch?v=3dxf1YNvCL8"
        ]
    },
     {
        "title": "The Art of Sarah",
        "urls": [
            "https://www.youtube.com/watch?v=D6gwMcL9OVM",
            "https://www.youtube.com/watch?v=D0kt6A8ZaKI"
        ]
    }
]

print("셀 3 완료: 5개 작품, 작품당 영상 2개, 영상당 댓글 150개로 설정되었습니다.")

def extract_video_id(url):
    url = url.strip()

    if re.fullmatch(r"[A-Za-z0-9_-]{11}", url):
        return url

    parsed = urlparse(url)

    if "youtu.be" in parsed.netloc:
        return parsed.path.strip("/").split("/")[0]

    if "youtube.com" in parsed.netloc:
        if parsed.path == "/watch":
            return parse_qs(parsed.query).get("v", [None])[0]

        if parsed.path.startswith("/shorts/"):
            return parsed.path.split("/")[2]

        if parsed.path.startswith("/embed/"):
            return parsed.path.split("/")[2]

    return None

print("셀 4 완료: 영상 ID 추출 함수가 준비되었습니다.")

def fetch_comments(video_id, title, video_url, max_comments=100):
    rows = []
    next_page_token = None

    while len(rows) < max_comments:
        params = {
            "part": "snippet",
            "videoId": video_id,
            "maxResults": min(100, max_comments - len(rows)),
            "order": "relevance",
            "textFormat": "plainText",
            "key": API_KEY
        }

        if next_page_token:
            params["pageToken"] = next_page_token

        response = requests.get(
            "https://www.googleapis.com/youtube/v3/commentThreads",
            params=params
        )

        data = response.json()

        if "error" in data:
            print(f"[오류] {title} / {video_id}")
            print(data["error"])
            break

        items = data.get("items", [])

        if not items:
            break

        for item in items:
            comment = item["snippet"]["topLevelComment"]["snippet"]

            rows.append({
                "title": title,
                "video_id": video_id,
                "video_url": video_url,
                "comment_text": comment.get("textDisplay", ""),
                "like_count": comment.get("likeCount", 0),
                "published_at": comment.get("publishedAt", "")
            })

        next_page_token = data.get("nextPageToken")

        if not next_page_token:
            break

        time.sleep(0.2)

    return rows

print("셀 5 완료: 댓글 수집 함수가 준비되었습니다.")

all_rows = []

for work in works:
    title = work["title"]
    urls = work["urls"]

    print(f"\n수집 시작: {title}")

    for url in urls:
        video_id = extract_video_id(url)

        if not video_id:
            print(f"영상 ID를 찾지 못했습니다: {url}")
            continue

        print(f"댓글 수집 중: {video_id}")
        rows = fetch_comments(video_id, title, url, COMMENTS_PER_VIDEO)
        all_rows.extend(rows)

        print(f"이 영상에서 수집된 댓글 수: {len(rows)}")

df = pd.DataFrame(all_rows)

print("\n전체 수집 완료")
print("총 댓글 수:", len(df))

df.head()

def clean_text(text):
    text = str(text).lower()

    # 링크 제거
    text = re.sub(r"http\S+|www\S+", " ", text)

    # 영어, 한국어, 숫자, 공백만 남기기
    text = re.sub(r"[^a-zA-Z가-힣0-9\s]", " ", text)

    # 여러 개의 공백을 하나로 줄이기
    text = re.sub(r"\s+", " ", text).strip()

    return text

# 댓글 정리
df["clean_text"] = df["comment_text"].apply(clean_text)

# 너무 짧은 댓글 제거
before_count = len(df)
df = df[df["clean_text"].str.len() >= 10].copy()
after_short_filter = len(df)

# 중복 댓글 제거
df = df.drop_duplicates(subset=["title", "clean_text"]).copy()
after_duplicate_filter = len(df)

print("셀 7 완료: 댓글 정리가 끝났습니다.")
print("처음 댓글 수:", before_count)
print("짧은 댓글 제거 후:", after_short_filter)
print("중복 제거 후:", after_duplicate_filter)

df[["title", "comment_text", "clean_text"]].head(10)

stopwords = [
    # 영어 기본 단어
    "the", "and", "for", "are", "was", "were", "this", "that", "with",
    "you", "your", "have", "has", "had", "but", "not", "they", "them",
    "his", "her", "she", "him", "who", "what", "when", "where", "why",
    "how", "from", "just", "like", "very", "really", "also", "then",
    "than", "one", "two", "all", "can", "could", "would", "should",
    "there", "here", "about", "because", "after", "before", "more",
    "most", "much", "many", "some", "any", "every", "always", "will",
    "get", "got", "make", "made", "need", "needs", "please", "let",
    "know", "think", "going", "come", "coming", "cant", "can t",
    "don", "don t", "didn", "didn t", "isn", "isn t", "it", "its",
    "it s", "i", "me", "my", "we", "us", "our", "a", "an", "to",
    "of", "in", "on", "at", "by", "as", "or", "so", "if",

    # 유튜브/넷플릭스 댓글에서 너무 흔한 단어
    "watching", "watch", "watched", "trailer", "official", "netflix",
    "youtube", "video", "comment", "comments", "season", "seasons",
    "episode", "episodes", "show", "shows", "series", "movie", "film",
    "new", "next", "part", "parts", "release", "released",

    # 시간/연도 관련 단어
    "2021", "2022", "2023", "2024", "2025", "2026",
    "today", "tomorrow", "yesterday", "year", "years", "month", "months",
    "week", "weeks", "day", "days",

    # 자주 나오지만 분석 의미가 약한 감탄어
    "wow", "omg", "lol", "lmao", "haha", "yes", "no", "finally",
    "wait", "waiting", "soon", "again", "still",

    # 한국어 일반 단어
    "그리고", "근데", "진짜", "정말", "너무", "완전", "그냥",
    "이거", "저거", "이게", "저게", "ㅋㅋ", "ㅎㅎ", "ㅠㅠ",
    "보는", "봤다", "봤는데", "다시", "영상", "댓글", "예고편",
    "시즌", "넷플릭스"
]

print("셀 8 완료: 불필요한 단어 목록이 준비되었습니다.")
print("제외 단어 수:", len(stopwords))

documents = df.groupby("title")["clean_text"].apply(lambda x: " ".join(x)).reset_index()

vectorizer = CountVectorizer(
    stop_words=stopwords,
    ngram_range=(1, 2),
    min_df=1,
    token_pattern=r"(?u)\b[a-zA-Z가-힣][a-zA-Z가-힣0-9]+\b"
)

count_matrix = vectorizer.fit_transform(documents["clean_text"])
terms = vectorizer.get_feature_names_out()

count_df = pd.DataFrame(
    count_matrix.toarray(),
    index=documents["title"],
    columns=terms
)

print("셀 9 완료: 단어 빈도 분석이 끝났습니다.")
print("분석한 작품 수:", len(count_df))
print("분석된 단어/표현 수:", len(terms))

count_df.head()

top_rows = []

for title in count_df.index:
    top_words = count_df.loc[title].sort_values(ascending=False).head(50)

    for rank, (word, count) in enumerate(top_words.items(), start=1):
        top_rows.append({
            "title": title,
            "rank": rank,
            "keyword": word,
            "count": int(count)
        })

top_word_table = pd.DataFrame(top_rows)

print("셀 10 완료: 작품별 TOP 단어표가 만들어졌습니다.")
print("총 행 수:", len(top_word_table))

top_word_table.head(50)

extra_stopwords = [
    # 아직 남아있는 영어 기본 단어
    "is", "am", "be", "been", "being",
    "now", "see", "ve", "he", "up", "do", "did", "done",
    "back", "time", "long", "last", "first", "well",
    "man", "guy", "guys", "thing", "things",
    "s4", "s3", "s2", "s1",

    # 감탄/기대 표현 중 분석 의미가 약한 것
    "hope", "hoping", "glad", "excited", "looking", "forward",
    "looking forward", "finished", "already", "october",

    # 제목에서만 반복될 수 있는 단어
    "lincoln"
]

stopwords = stopwords + extra_stopwords

print("셀 8-1 완료: 불필요한 단어가 추가되었습니다.")
print("전체 제외 단어 수:", len(stopwords))

sentiment_words = [
    "love", "love love", "great", "good", "best", "amazing", "awesome",
    "better", "favourite", "favorite", "fav", "absolutely", "loved",
    "underrated", "excellent", "perfect", "brilliant", "masterpiece",
    "excited", "glad", "ready"
]

weak_words = [
    "ever", "damn", "oh", "want", "cannot", "go", "out", "bring",
    "another", "their", "only", "whole", "looks", "neve", "re",
    "getting", "never"
]

def classify_keyword_type(keyword):
    keyword = str(keyword).lower()

    if keyword in sentiment_words:
        return "감상/호평"

    if keyword in weak_words:
        return "맥락확인필요"

    return "콘텐츠요소"

top_word_table["keyword_type"] = top_word_table["keyword"].apply(classify_keyword_type)

print("셀 11 완료: 키워드 종류가 추가되었습니다.")

top_word_table.head(50)

tfidf_vectorizer = TfidfVectorizer(
    stop_words=stopwords,
    ngram_range=(1, 2),
    min_df=1,
    token_pattern=r"(?u)\b[a-zA-Z가-힣][a-zA-Z가-힣0-9]+\b"
)

tfidf_matrix = tfidf_vectorizer.fit_transform(documents["clean_text"])
tfidf_terms = tfidf_vectorizer.get_feature_names_out()

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=documents["title"],
    columns=tfidf_terms
)

tfidf_rows = []

for title in tfidf_df.index:
    top_words = tfidf_df.loc[title].sort_values(ascending=False).head(50)

    for rank, (word, score) in enumerate(top_words.items(), start=1):
        tfidf_rows.append({
            "title": title,
            "rank": rank,
            "keyword": word,
            "tfidf_score": round(float(score), 4)
        })

tfidf_table = pd.DataFrame(tfidf_rows)

# TF-IDF 키워드에도 종류 붙이기
tfidf_table["keyword_type"] = tfidf_table["keyword"].apply(classify_keyword_type)

print("셀 12 완료: TF-IDF 분석표가 만들어졌습니다.")
print("총 행 수:", len(tfidf_table))

tfidf_table.head(50)

summary_rows = []

for title in top_word_table["title"].unique():
    title_top = top_word_table[top_word_table["title"] == title]
    title_tfidf = tfidf_table[tfidf_table["title"] == title]

    sentiment_keywords = title_top[
        title_top["keyword_type"] == "감상/호평"
    ].head(20)

    content_keywords = title_top[
        title_top["keyword_type"] == "콘텐츠요소"
    ].head(35)

    tfidf_keywords = title_tfidf.head(30)

    summary_rows.append({
        "title": title,
        "total_cleaned_comments": int(df[df["title"] == title].shape[0]),

        "top_sentiment_keywords_count": ", ".join(
            [f"{row.keyword}({row.count})" for row in sentiment_keywords.itertuples()]
        ),

        "top_content_keywords_count": ", ".join(
            [f"{row.keyword}({row.count})" for row in content_keywords.itertuples()]
        ),

        "top_tfidf_keywords": ", ".join(
            [f"{row.keyword}({row.tfidf_score})" for row in tfidf_keywords.itertuples()]
        ),

        "analyst_interpretation": ""
    })

interpretation_summary = pd.DataFrame(summary_rows)

print("셀 13 완료: 작품별 요약표가 만들어졌습니다.")
interpretation_summary

summary_exclude_words = [
    # 영어 잡음
    "is", "am", "are", "be", "been", "being",
    "back", "time", "now", "see", "ve", "he", "she",
    "up", "do", "did", "done", "go", "out", "their",
    "only", "whole", "another", "cannot", "bring",
    "getting", "never", "looks", "look", "want",

    # 독일어/유럽권 댓글에서 자주 나오는 일반어
    "ich", "der", "die", "das", "zu", "er", "sie",
    "und", "ist", "ein", "eine", "nicht", "mit", "auf",
    "für", "wir", "ihr", "im", "den", "dem"
]

summary_rows = []

for title in top_word_table["title"].unique():
    title_top = top_word_table[top_word_table["title"] == title].copy()
    title_tfidf = tfidf_table[tfidf_table["title"] == title].copy()

    # 요약표에서만 잡음 단어 제외
    title_top = title_top[~title_top["keyword"].isin(summary_exclude_words)]
    title_tfidf = title_tfidf[~title_tfidf["keyword"].isin(summary_exclude_words)]

    sentiment_keywords = title_top[
        title_top["keyword_type"] == "감상/호평"
    ].head(20)

    content_keywords = title_top[
        title_top["keyword_type"] == "콘텐츠요소"
    ].head(35)

    tfidf_keywords = title_tfidf.head(30)

    summary_rows.append({
        "title": title,
        "total_cleaned_comments": int(df[df["title"] == title].shape[0]),

        "top_sentiment_keywords_count": ", ".join(
            [f"{row.keyword}({row.count})" for row in sentiment_keywords.itertuples()]
        ),

        "top_content_keywords_count": ", ".join(
            [f"{row.keyword}({row.count})" for row in content_keywords.itertuples()]
        ),

        "top_tfidf_keywords": ", ".join(
            [f"{row.keyword}({row.tfidf_score})" for row in tfidf_keywords.itertuples()]
        ),

        "analyst_interpretation": ""
    })

interpretation_summary = pd.DataFrame(summary_rows)

print("셀 13-1 완료: 요약표가 더 깔끔하게 다시 만들어졌습니다.")
interpretation_summary

sample_comments = (
    df.sort_values(["title", "like_count"], ascending=[True, False])
      .groupby("title")
      .head(30)
      [["title", "video_id", "video_url", "comment_text", "clean_text", "like_count", "published_at"]]
      .reset_index(drop=True)
)

print("셀 14 완료: 작품별 좋아요 높은 댓글 표본이 만들어졌습니다.")
print("총 표본 댓글 수:", len(sample_comments))

sample_comments.head(30)

data_summary_rows = []

for work in works:
    title = work["title"]
    urls = work["urls"]

    collected_count = int(len(df[df["title"] == title]))

    data_summary_rows.append({
        "title": title,
        "youtube_urls": "\n".join(urls),
        "target_comments_per_video": COMMENTS_PER_VIDEO,
        "number_of_videos": len(urls),
        "cleaned_comments_used": collected_count,
        "data_source": "YouTube Data API",
        "why_chosen": "YouTube comments were selected because they provide direct viewer reactions to Netflix-related trailers and official videos. They are useful for identifying repeated audience interests, emotional reactions, and content elements."
    })

data_summary = pd.DataFrame(data_summary_rows)

print("셀 15 완료: 데이터 수집 요약표가 만들어졌습니다.")
data_summary

method_notes = pd.DataFrame([
    {
        "step": 1,
        "method": "Data Collection",
        "description": "Viewer comments were collected from YouTube videos related to selected Netflix series using the YouTube Data API.",
        "purpose": "To collect direct audience reaction data from online video platforms."
    },
    {
        "step": 2,
        "method": "Text Cleaning",
        "description": "URLs, special characters, emojis, and extra spaces were removed. Comments that were too short were excluded, and duplicate comments were removed.",
        "purpose": "To prepare the comments for text mining while preserving most of the original viewer responses."
    },
    {
        "step": 3,
        "method": "Keyword Frequency Analysis",
        "description": "The cleaned comments were tokenized into words and two-word phrases. Common stopwords were removed, and the most frequent keywords were extracted for each title.",
        "purpose": "To identify repeatedly mentioned words and phrases in viewer reactions."
    },
    {
        "step": 4,
        "method": "Keyword Type Classification",
        "description": "Frequent keywords were categorized into broad types such as sentiment/praise keywords and content-element keywords.",
        "purpose": "To distinguish general audience approval from specific content features such as character, genre, story, acting, and suspense."
    },
    {
        "step": 5,
        "method": "TF-IDF Analysis",
        "description": "TF-IDF was used to identify keywords that were especially distinctive for each title compared with the other titles.",
        "purpose": "To find title-specific themes, genre signals, and story elements."
    },
    {
        "step": 6,
        "method": "Evidence Sampling",
        "description": "For each title, the 30 comments with the highest like counts were extracted as sample audience reactions.",
        "purpose": "To provide qualitative evidence that supports the keyword-based findings."
    }
])

print("셀 16 완료: 분석 방법 설명표가 만들어졌습니다.")
method_notes

output_file = "streamkus_youtube_text_mining_dataset.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    data_summary.to_excel(writer, sheet_name="1_data_summary", index=False)
    df.to_excel(writer, sheet_name="2_cleaned_comments_all", index=False)
    top_word_table.to_excel(writer, sheet_name="3_keyword_top50", index=False)
    tfidf_table.to_excel(writer, sheet_name="4_tfidf_top50", index=False)
    interpretation_summary.to_excel(writer, sheet_name="5_interpretation_summary", index=False)
    sample_comments.to_excel(writer, sheet_name="6_sample_comments_top30", index=False)
    method_notes.to_excel(writer, sheet_name="7_method_notes", index=False)

files.download(output_file)

print("셀 17 완료: 최종 엑셀 파일이 만들어졌습니다.")
print("파일 이름:", output_file)